In [27]:
import pandas as pd

df = pd.read_csv('dialogs.txt', delimiter = '\t')
df.head()

Question  \
0               hi, how are you doing?   
1        i'm fine. how about yourself?   
2  i'm pretty good. thanks for asking.   
3    no problem. so how have you been?   
4     i've been great. what about you?   

                                   Response  
0             i'm fine. how about yourself?  
1       i'm pretty good. thanks for asking.  
2         no problem. so how have you been?  
3          i've been great. what about you?  
4  i've been good. i'm in school right now.

In [28]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [29]:
from nltk.tokenize import word_tokenize

def tokenize(x):
  words = word_tokenize(x)
  return words

tokenize("Kausik Kar is a good person.")

['Kausik', 'Kar', 'is', 'a', 'good', 'person', '.']

In [30]:
df['Question'] = df['Question'].apply(tokenize)
df['Response'] = df['Response'].apply(tokenize)

df.head()

Question  \
0                  [hi, ,, how, are, you, doing, ?]   
1         [i, 'm, fine, ., how, about, yourself, ?]   
2  [i, 'm, pretty, good, ., thanks, for, asking, .]   
3     [no, problem, ., so, how, have, you, been, ?]   
4     [i, 've, been, great, ., what, about, you, ?]   

                                            Response  
0          [i, 'm, fine, ., how, about, yourself, ?]  
1   [i, 'm, pretty, good, ., thanks, for, asking, .]  
2      [no, problem, ., so, how, have, you, been, ?]  
3      [i, 've, been, great, ., what, about, you, ?]  
4  [i, 've, been, good, ., i, 'm, in, school, rig...

In [31]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatizing(x):
  word_ls = []

  for word in x:
    w = lemmatizer.lemmatize(word)
    word_ls.append(w)

  return word_ls

In [32]:
lemmatizing(['hi','' ,'', 'how', 'are', 'you', 'doing', '?'])

['hi', '', '', 'how', 'are', 'you', 'doing', '?']

In [33]:
df['Question'] = df['Question'].apply(lemmatizing)
df['Response'] = df['Response'].apply(lemmatizing)

df.head()

Question  \
0                  [hi, ,, how, are, you, doing, ?]   
1         [i, 'm, fine, ., how, about, yourself, ?]   
2  [i, 'm, pretty, good, ., thanks, for, asking, .]   
3     [no, problem, ., so, how, have, you, been, ?]   
4     [i, 've, been, great, ., what, about, you, ?]   

                                            Response  
0          [i, 'm, fine, ., how, about, yourself, ?]  
1   [i, 'm, pretty, good, ., thanks, for, asking, .]  
2      [no, problem, ., so, how, have, you, been, ?]  
3      [i, 've, been, great, ., what, about, you, ?]  
4  [i, 've, been, good, ., i, 'm, in, school, rig...

In [34]:
removal = ['',',', '.', '?', ':', ';']

def removing(x):
  for z in x:
    if(z in removal):
      x.remove(z)

  return x

df['Question'] = df['Question'].apply(removing)
df['Response'] = df['Response'].apply(removing)

df.head()

Question  \
0                  [hi, how, are, you, doing]   
1         [i, 'm, fine, how, about, yourself]   
2  [i, 'm, pretty, good, thanks, for, asking]   
3     [no, problem, so, how, have, you, been]   
4     [i, 've, been, great, what, about, you]   

                                            Response  
0                [i, 'm, fine, how, about, yourself]  
1         [i, 'm, pretty, good, thanks, for, asking]  
2            [no, problem, so, how, have, you, been]  
3            [i, 've, been, great, what, about, you]  
4  [i, 've, been, good, i, 'm, in, school, right,...

In [35]:
def convert_to_string(x):

  str_lst = []
  for word in x:
    c = str(word)
    str_lst.append(c)

  lst = []

  for word in str_lst:
    z = word.lower()
    lst.append(z)

  return lst


convert_to_string(["He", "is", "The", "No", 1, "Player"])

['he', 'is', 'the', 'no', '1', 'player']

In [36]:
df['Question'] = df['Question'].apply(convert_to_string)
df['Response'] = df['Response'].apply(convert_to_string)

df.head()

Question  \
0                  [hi, how, are, you, doing]   
1         [i, 'm, fine, how, about, yourself]   
2  [i, 'm, pretty, good, thanks, for, asking]   
3     [no, problem, so, how, have, you, been]   
4     [i, 've, been, great, what, about, you]   

                                            Response  
0                [i, 'm, fine, how, about, yourself]  
1         [i, 'm, pretty, good, thanks, for, asking]  
2            [no, problem, so, how, have, you, been]  
3            [i, 've, been, great, what, about, you]  
4  [i, 've, been, good, i, 'm, in, school, right,...

In [37]:
def joining(x):
  sentence = ""

  for word in x:
    sentence += word
    sentence += ' '

  return sentence

joining(['hi', 'how', 'are', 'you'])

'hi how are you '

In [38]:
df_training = pd.DataFrame()

df_training['Question'] = df['Question'].apply(joining)
df_training['Response'] = df['Response'].apply(joining)

df_training

Question  \
0                                 hi how are you doing    
1                         i 'm fine how about yourself    
2                   i 'm pretty good thanks for asking    
3                      no problem so how have you been    
4                      i 've been great what about you    
...                                                 ...   
3720   that 's a good question maybe it 's not old age    
3721                              are you right-handed    
3722                                   yes all my life    
3723  you 're wearing out your right hand stop using...   
3724        but i do all my writing with my right hand    

                                               Response  
0                         i 'm fine how about yourself   
1                   i 'm pretty good thanks for asking   
2                      no problem so how have you been   
3                      i 've been great what about you   
4             i 've been good i 'm in school right now   
...                                                 ...  
3720                              are you right-handed   
3721                                   yes all my life   
3722  you 're wearing out your right hand stop using...  
3723        but i do all my writing with my right hand   
3724  start typing instead that way your left hand w...  

[3725 rows x 2 columns]

In [39]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [40]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df_training['Question'])
total_words = len(tokenizer.word_index) + 1

In [41]:
X_seq = tokenizer.texts_to_sequences(df_training['Question'])

In [42]:
max_sequence_length = max(len(seq) for seq in X_seq)

In [43]:
max_sequence_length

20

In [44]:
X_padded = pad_sequences(X_seq, maxlen=max_sequence_length, padding='post')

In [45]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_length))
model.add(LSTM(200))
model.add(Dense(3506, activation='softmax'))

In [46]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [47]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(df_training['Response'])
y

array([ 740,  784, 1840, ..., 3381,  220, 2267])

In [48]:
y

array([ 740,  784, 1840, ..., 3381,  220, 2267])

In [49]:
from tensorflow.keras.utils import to_categorical

# Assuming y_train is your original target variable
y_train_one_hot = to_categorical(y, num_classes=3506)
y_train_one_hot

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [50]:
y_train_one_hot.shape

(3725, 3506)

In [51]:
import tensorflow as tf
tf.random.set_seed(0)
model.fit(X_padded, y_train_one_hot, epochs=50)

Epoch 1/50
117/117 [==============================] - 6s 36ms/step - loss: 8.1796 - accuracy: 2.6846e-04
Epoch 2/50
117/117 [==============================] - 5s 39ms/step - loss: 8.1914 - accuracy: 2.6846e-04
Epoch 3/50
117/117 [==============================] - 4s 37ms/step - loss: 8.1651 - accuracy: 0.0054
Epoch 4/50
117/117 [==============================] - 4s 35ms/step - loss: 8.1559 - accuracy: 0.0067
Epoch 5/50
117/117 [==============================] - 5s 39ms/step - loss: 8.1278 - accuracy: 0.0051
Epoch 6/50
117/117 [==============================] - 4s 34ms/step - loss: 7.9772 - accuracy: 0.0027
Epoch 7/50
117/117 [==============================] - 4s 34ms/step - loss: 7.6389 - accuracy: 0.0043
Epoch 8/50
117/117 [==============================] - 5s 39ms/step - loss: 7.1622 - accuracy: 0.0062
Epoch 9/50
117/117 [==============================] - 4s 35ms/step - loss: 6.6163 - accuracy: 0.0089
Epoch 10/50
117/117 [==============================] - 4s 37ms/step - loss: 6.0783 

In [52]:
question = "What are you eating?"

question_seq = tokenizer.texts_to_sequences([question])
question_padded = pad_sequences(question_seq, maxlen=max_sequence_length, padding='post')

In [53]:
question_padded

array([[ 11,  17,   2, 465,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0]], dtype=int32)

In [54]:
resp = model.predict(question_padded)

1/1 [==============================] - 0s 308ms/step


In [55]:
resp

array([[1.4420259e-06, 2.2426932e-06, 2.6725493e-07, ..., 9.5066446e-07,
        2.3739222e-09, 3.4083907e-08]], dtype=float32)

In [56]:
x = np.argmax(resp[0])

In [57]:
lst = np.array([x])
lst

array([768])

In [58]:
v = le.inverse_transform(lst)
v

array(["i 'm looking there 's nothing to eat "], dtype=object)

In [59]:
def chatting(question):
  question_seq = tokenizer.texts_to_sequences([question])
  question_padded = pad_sequences(question_seq, maxlen=max_sequence_length, padding='post')
  resp = model.predict(question_padded)
  x = np.argmax(resp[0])
  lst = np.array([x])
  v = le.inverse_transform(lst)
  return v

In [60]:
chatting("How you have been doing?")

1/1 [==============================] - 0s 16ms/step


array(['i bought lot of orange and apple '], dtype=object)

In [61]:
chatting("Hope you are fine")

1/1 [==============================] - 0s 18ms/step


array(['my wife left me '], dtype=object)

In [62]:
chatting("Is everything okay")

1/1 [==============================] - 0s 17ms/step


array(["i did n't know that "], dtype=object)

In [63]:
chatting("What else is happening")

1/1 [==============================] - 0s 18ms/step


array(['nope and it drive him crazy '], dtype=object)

In [64]:
chatting("I am hungry")

1/1 [==============================] - 0s 18ms/step


array(['with toast ham sausage fresh fruit and juice '], dtype=object)

In [65]:
chatting("Where are you?")

1/1 [==============================] - 0s 19ms/step


array(['what kind of car do you have '], dtype=object)

In [66]:
chatting("Where is the food")

1/1 [==============================] - 0s 18ms/step


array(["i really wish it wa n't so hot every day "], dtype=object)